import type { RequestHandler } from './$types';
import { SafeFetchError, describeSafeFetchError } from '$lib/server/safeFetch';
import { decodePageFeedParams } from '$lib/pageFeed';
import { parseSignedQuery, verifyPageFeedSignature } from '$lib/server/pageFeed/sign';
import { validatePageFeedConfig } from '$lib/server/pageFeed/validate';
import { getPageFeedSecret } from '$lib/server/pageFeed/secret';
import { fetchPageCached } from '$lib/server/pageFeed/pageCache';
import { UPSTREAM_FAILED } from '$lib/server/sourcePage';
import {
	InvalidPatternError,
	InvalidSelectorError,
	extractItems,
	parsePage
} from '$lib/server/pageFeed/extract';
import { buildRss, rssEtag } from '$lib/server/pageFeed/rss';

// The feed Miniflux polls. Deliberately unauthenticated — Miniflux's crawler can't send our
// headers — so the HMAC signature over the query is the whole gate: only URLs minted by
// /api/page-feed/preview for a logged-in user verify, and nothing else can turn this into a
// fetch-anything proxy. Per-IP rate limit in hooks.server.ts.
//
// Errors are plain text: Miniflux surfaces the status as the feed's parsing error, which is
// exactly where the user will look.

const PAGE_MAX_AGE_MS = 60_000;

function text(status: number, message: string): Response {
	return new Response(message, {
		status,
		headers: { 'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'no-store' }
	});
}

export const GET: RequestHandler = async ({ request, url }) => {
	const signed = parseSignedQuery(url.searchParams);
	if (!signed) return text(400, 'Malformed page-feed URL');
	if (!verifyPageFeedSignature(signed.params, signed.sig, getPageFeedSecret())) {
		return text(403, 'Invalid page-feed signature');
	}
	const config = decodePageFeedParams(signed.params);
	if (!config) return text(400, 'Malformed page-feed URL');
	const problem = validatePageFeedConfig(config);
	if (problem) return text(400, problem);

	let page;
	try {
		page = await fetchPageCached(config.pageUrl, PAGE_MAX_AGE_MS);
	} catch (e) {
		if (e instanceof SafeFetchError) return text(e.isPolicy ? 400 : UPSTREAM_FAILED, describeSafeFetchError(e));
		return text(UPSTREAM_FAILED, 'Failed to fetch the page');
	}
	if (!page.ok) return text(UPSTREAM_FAILED, `Source returned ${page.status}`);

	let result;
	try {
		result = extractItems(parsePage(page.html), config.pageUrl, config);
	} catch (e) {
		// Only reachable if a signed selector/pattern stopped parsing after a library upgrade.
		if (e instanceof InvalidSelectorError || e instanceof InvalidPatternError) return text(400, e.message);
		throw e;
	}

	const source = new URL(config.pageUrl);
	const body = buildRss(
		{
			title: result.pageTitle || source.host + source.pathname,
			link: config.pageUrl,
			description: `Generated by Miniflux Reader from ${config.pageUrl}`,
			selfUrl: url.origin + url.pathname + url.search
		},
		result.items
	);

	// no-cache = always revalidate: Cloudflare must not serve a stale copy, but Miniflux's
	// If-None-Match gets a cheap 304 whenever the extraction is byte-identical.
	const etag = rssEtag(body);
	const headers: Record<string, string> = { ETag: etag, 'Cache-Control': 'no-cache' };
	if (request.headers.get('if-none-match') === etag) return new Response(null, { status: 304, headers });
	return new Response(body, {
		status: 200,
		headers: { ...headers, 'Content-Type': 'application/rss+xml; charset=utf-8' }
	});
};
