<script lang="ts">
	import { FlaskConical } from 'lucide-svelte';
	import PageFeedFields from '$lib/components/ui/PageFeedFields.svelte';
	import PageFeedPreviewList from '$lib/components/ui/PageFeedPreviewList.svelte';
	import {
		pageFeedConfigKey,
		type PageFeedConfig,
		type PageFeedItem,
		type PageFeedSigned
	} from '$lib/pageFeed';
	import { previewPageFeed } from '$lib/pageFeedClient';

	// Edits a Miniflux Reader page feed (see $lib/pageFeed). The signed URL is the config, so a change
	// has to go through the server once — Preview validates it, shows the items and hands back
	// the re-signed URL that Save then writes to Miniflux as feed_url.
	let {
		active,
		config = $bindable(),
		signed = $bindable(),
		initialKey,
		storedFeedUrl
	}: {
		active: boolean;
		config: PageFeedConfig;
		signed: PageFeedSigned | null;
		initialKey: string; // pageFeedConfigKey of the config Miniflux currently has
		storedFeedUrl: string; // the feed_url Miniflux currently has
	} = $props();

	let previewing = $state(false);
	let error = $state('');
	let items = $state.raw<PageFeedItem[]>([]);
	let matched = $state(0);
	let previewedKey = $state('');

	const key = $derived(pageFeedConfigKey(config));
	const ready = $derived(!!config.pageUrl.trim() && !!config.itemSelector.trim());
	// Edited, but not yet validated/signed — Save stays off until Preview has run for this config.
	const stale = $derived(key !== initialKey && signed?.key !== key);
	// Same config, different signature: the server's key changed since this URL was minted.
	const resigned = $derived(signed !== null && signed.key === initialKey && signed.feedUrl !== storedFeedUrl);

	async function preview() {
		if (previewing || !ready) return;
		previewing = true;
		error = '';
		const cfg = $state.snapshot(config);
		const cfgKey = pageFeedConfigKey(cfg);
		try {
			const res = await previewPageFeed(cfg);
			items = res.items ?? [];
			matched = res.matched ?? 0;
			previewedKey = cfgKey;
			if (res.feedUrl) signed = { key: cfgKey, feedUrl: res.feedUrl };
		} catch (e) {
			error = e instanceof Error ? e.message : 'Preview failed';
		} finally {
			previewing = false;
		}
	}
</script>

<section class:hidden={!active} class="rounded-lg border border-n-100 bg-surface p-5 shadow-xl">
	<h3 class="mb-4 text-sm font-semibold uppercase tracking-wide text-n-500">Page feed</h3>

	<p class="mb-4 text-xs text-n-500">
		This feed is generated by Miniflux Reader from a listing page. Change the page or the selectors,
		Preview to check the result and sign the new feed URL, then Save. Refresh the feed afterwards
		to re-pull entries from the new URL.
	</p>

	<div class="space-y-4">
		<div>
			<label for="pfs-page-url" class="mb-1 block text-sm font-medium text-n-700">Page URL</label>
			<input
				id="pfs-page-url"
				type="url"
				bind:value={config.pageUrl}
				placeholder="https://example.com/tag/topic"
				class="w-full rounded-md border border-n-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-n-400"
			/>
		</div>

		<PageFeedFields bind:config idPrefix="pfs" />

		<div class="flex items-center gap-3">
			<button
				type="button"
				onclick={preview}
				disabled={previewing || !ready}
				class="inline-flex items-center gap-1.5 rounded-md border border-n-300 px-3 py-2 text-sm text-n-700 hover:bg-n-100 disabled:opacity-50"
			>
				<FlaskConical class={`h-3.5 w-3.5 ${previewing ? 'animate-pulse' : ''}`} />
				{previewing ? 'Previewing…' : 'Preview'}
			</button>
			{#if stale}
				<span class="text-xs text-warning">Changed — preview to validate and sign before saving.</span>
			{:else if resigned}
				<span class="text-xs text-n-500">The stored URL was signed with an older key — Save to re-sign it.</span>
			{/if}
		</div>

		{#if error}
			<p class="text-xs text-danger">{error}</p>
		{:else if previewedKey === key}
			<PageFeedPreviewList {items} {matched} />
		{/if}
	</div>
</section>
