<script lang="ts">
	import type { Feed } from '$lib/types';
	import { AlertTriangle } from 'lucide-svelte';
	import { relaTimestamp } from '$lib/time';
	import { normalizeLang } from '$lib/lang';
	import { caps } from '$lib/backend';
	import CategorySelect from '$lib/components/ui/CategorySelect.svelte';

	let {
		active,
		feed,
		entryCount,
		title = $bindable(),
		categoryId = $bindable(),
		newCategoryName = $bindable(),
		siteUrl = $bindable(),
		rssSourceUrl = $bindable(),
		feedUrlManagedBy,
		effectiveFeedUrl
	}: {
		active: boolean;
		feed: Feed;
		entryCount: number | null;
		title: string;
		categoryId: number;
		newCategoryName: string;
		siteUrl: string;
		rssSourceUrl: string;
		// When set, the feed URL is assembled elsewhere (RSS-Bridge params, page-feed config) and
		// shown read-only here; null means the user edits it directly.
		feedUrlManagedBy: 'rss-bridge' | 'page-feed' | null;
		effectiveFeedUrl: string;
	} = $props();

	// Shown, not edited: Miniflux reads this from the feed itself (2.3.3+) and its API has no
	// field to override it. It earns the row by explaining why this feed's articles do or don't
	// carry a lang attribute — and an empty value doubles as "not re-parsed since the upgrade".
	const language = $derived(normalizeLang(feed.language));
	const languageHint = $derived(
		language
			? 'Declared by the feed. Its titles and article text are tagged with this language, so screen readers, hyphenation and translation offers follow it.'
			: 'Not declared by the feed — or the feed has not been re-parsed since Miniflux 2.3.3, which is the first version to read it. Its text keeps the page language.'
	);

	const label = 'mb-1.5 block text-[13px] font-medium text-n-700';
	const field = 'h-9.5 w-full rounded-lg border border-n-300 bg-surface px-3 text-sm text-n-900 field-focus';
	const bigField = 'h-10 w-full rounded-lg border border-n-300 bg-surface px-3 text-[15px] text-n-900 field-focus';
	const stat = 'font-semibold text-n-700';
</script>

<section class:hidden={!active} class="rounded-xl bg-surface px-8 py-7 shadow-card max-md:px-5 max-md:py-5">
	<div class="mb-4.5">
		<h3 class="text-base font-bold text-n-900">General</h3>
		<p class="mt-0.5 text-[12.5px] text-n-500">
			Last refresh <b class={stat} title={feed.checked_at ?? ''}>{feed.checked_at ? `${relaTimestamp(feed.checked_at)} ago` : '—'}</b>
			· <b class={stat}>{entryCount ?? '—'}</b> entries
			· <span title={languageHint}>Language <b class={stat}>{language ?? '—'}</b></span>
		</p>
	</div>

	{#if feed.parsing_error_count && feed.parsing_error_count > 0}
		<div class="mb-4.5 rounded-lg border border-danger/40 bg-danger/10 px-4 py-2.5 text-danger">
			<p class="flex items-center gap-1.5 text-sm font-medium">
				<AlertTriangle class="h-4 w-4 shrink-0" />
				Parsing errors {feed.parsing_error_count}×
			</p>
			{#if feed.parsing_error_message}
				<p class="mt-1 text-[13px]">{feed.parsing_error_message}</p>
			{/if}
		</div>
	{/if}

	<div class="flex flex-col gap-4.5">
		<div class="grid gap-4 sm:grid-cols-[2fr_1fr]">
			<div class="min-w-0">
				<label for="feed-title" class={label}>Title</label>
				<input id="feed-title" type="text" bind:value={title} class="{bigField} font-semibold" />
			</div>
			<div class="min-w-0">
				<label for="feed-category" class={label}>Category</label>
				<CategorySelect
					id="feed-category"
					bind:value={categoryId}
					bind:newName={newCategoryName}
					selectClass={bigField}
					inputClass="mt-2 {bigField}"
				/>
			</div>
		</div>

		<div>
			<label for="feed-feed-url" class={label}>Feed URL</label>
			{#if feedUrlManagedBy}
				<input
					id="feed-feed-url"
					type="url"
					value={effectiveFeedUrl || '— preview in the Page Feed tab to generate —'}
					readonly
					class="h-9.5 w-full rounded-lg border border-n-200 bg-n-50 px-3 text-sm text-n-500 outline-none"
				/>
				<p class="mt-1.5 text-xs text-n-500">
					{#if feedUrlManagedBy === 'page-feed'}
						Generated by Miniflux Reader from a listing page — edit the page and selectors in the Page Feed tab.
					{:else}
						Managed by RSS-Bridge — edit its parameters in the RSS-Bridge tab, or disable it there to set a direct URL.
					{/if}
				</p>
			{:else}
				<input id="feed-feed-url" type="url" bind:value={rssSourceUrl} class={field} />
				{#if caps().rssBridge}
					<p class="mt-1.5 text-xs text-n-500">
						Direct URL. Enable RSS-Bridge to assemble it from bridge parameters instead.
					</p>
				{/if}
			{/if}
		</div>

		<div>
			<label for="feed-site-url" class={label}>Site URL</label>
			<input id="feed-site-url" type="url" bind:value={siteUrl} class={field} />
		</div>
	</div>
</section>
